"""Scaffolding for new tenants and domain packs.

These helpers generate boilerplate so forking the framework for a new business
is a one-command affair:

* ``create_tenant`` writes ``tenants/<id>.json`` with a minimal valid config.
* ``create_pack`` writes a ``<module>/pack.py`` exposing ``DOMAIN`` + ``register``.
"""

from __future__ import annotations

import json
from pathlib import Path

_PACK_TEMPLATE = '''"""Domain pack for {domain}.

Generated by `agentkit new-pack`. Flesh out the skill handler and schemas, then
turn the domain on by adding "{domain}" to a tenant's enabled_domains.
"""

from __future__ import annotations

from agentkit.core.contracts import (
    AgentProfile,
    SkillContext,
    SkillDefinition,
)
from agentkit.core.registry import AgentRegistry, SkillRegistry, ToolRegistry

DOMAIN = "{domain}"


def {handler}(ctx: SkillContext, args: dict) -> dict:
    """Replace with real business logic."""
    return {{"echo": args}}


def register(
    *,
    agents: AgentRegistry,
    skills: SkillRegistry,
    tools: ToolRegistry,
    tenant_config: dict,
) -> None:
    prompt_files = tenant_config.get("prompt_files", {{}})

    agents.register(
        AgentProfile(
            name="{agent}",
            domain=DOMAIN,
            description="Agent for the {domain} domain.",
            allowed_skills=["{skill}"],
            allowed_tools=[],
            prompt_file=prompt_files.get("agents.{agent}", ""),
        )
    )

    skills.register(
        SkillDefinition(
            name="{skill}",
            domain=DOMAIN,
            description="Example skill for {domain}.",
            input_schema={{
                "type": "object",
                "properties": {{}},
            }},
            output_schema={{
                "type": "object",
                "properties": {{"echo": {{"type": "object"}}}},
            }},
            permissions=[],
            execution_mode="plan_execute",
            tools=[],
            handler={handler},
            keywords=[],
        )
    )
'''


def _module_name(domain: str) -> str:
    """Python-safe module name for a domain (billing.invoices -> billing_invoices)."""
    return domain.replace(".", "_").replace("-", "_")


def _agent_name(domain: str) -> str:
    return _module_name(domain).split("_")[0] + "_agent"


def render_tenant_config(tenant_id: str) -> str:
    config = {
        "tenant_id": tenant_id,
        "enabled_domains": [],
        "approval_required_skills": [],
        "domain_personas": {},
        "prompt_files": {},
        "prompts": {},
    }
    return json.dumps(config, ensure_ascii=False, indent=2) + "\n"


def render_pack_module(domain: str) -> tuple[str, str]:
    """Return ``(init_source, pack_source)`` for a new pack."""
    module = _module_name(domain)
    skill = f"{module}.run"
    init_source = f'"""Domain pack for {domain}."""\n'
    pack_source = _PACK_TEMPLATE.format(
        domain=domain,
        handler=f"run_{module}",
        agent=_agent_name(domain),
        skill=skill,
    )
    return init_source, pack_source


def create_tenant(tenant_id: str, *, root: Path, force: bool = False) -> Path:
    """Write ``<root>/<tenant_id>.json``. Refuses to overwrite unless ``force``."""
    root = Path(root)
    root.mkdir(parents=True, exist_ok=True)
    path = root / f"{tenant_id}.json"
    if path.exists() and not force:
        raise FileExistsError(f"Tenant config already exists: {path}")
    path.write_text(render_tenant_config(tenant_id), encoding="utf-8")
    return path


def create_pack(domain: str, *, src_root: Path, force: bool = False) -> Path:
    """Write a pack package under ``<src_root>/<module>/``. Returns the package dir.

    Refuses to overwrite an existing pack unless ``force``.
    """
    src_root = Path(src_root)
    module = _module_name(domain)
    pack_dir = src_root / module
    pack_file = pack_dir / "pack.py"
    if pack_file.exists() and not force:
        raise FileExistsError(f"Pack already exists: {pack_file}")
    pack_dir.mkdir(parents=True, exist_ok=True)
    init_source, pack_source = render_pack_module(domain)
    (pack_dir / "__init__.py").write_text(init_source, encoding="utf-8")
    pack_file.write_text(pack_source, encoding="utf-8")
    return pack_dir


__all__ = [
    "render_tenant_config",
    "render_pack_module",
    "create_tenant",
    "create_pack",
]
